# Generated by Django 4.2.4 on 2023-08-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
